### ISSUE TITLE
Outdated API groups in chart

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#8]
In #2, the helm chart has outdated API groups. When installing on a modern microk8s cluster:

```shell
W0125 16:46:55.554047   72890 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable 
in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
microkW0125 16:46:57.569877   72890 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavai
lable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0125 16:46:58.994128   72890 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22
+; use rbac.authorization.k8s.io/v1 ClusterRole
W0125 16:46:59.152679   72890 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22
+; use rbac.authorization.k8s.io/v1 ClusterRole
```

The chart should be updated to use the new groups/versions.

**Comment by khaosdoctor** [comment]
I think this has been addressed on #2, I checked the files and they are already on the v1 version. I think this issue can be closed

**Comment by arschles** [comment]
@khaosdoctor I still get the error on https://github.com/kedacore/http-add-on/commit/7502948b6b83ac92a0b72828e62490400fe107fd on a 1.19.6 cluster. Here are the errors I get:

```shell
http-add-on on 🌲 main Go 🐹  v1.15.4 git rev-parse --short HEAD
7502948

http-add-on on 🌲 main Go 🐹  v1.15.4 make helm-upgrade-operator
helm upgrade kedahttp ./charts/keda-http-operator \
    --install \
    --namespace kedahttp \
    --create-namespace \
    --set image=arschles/keda-http-operator:7502948 \
--set externalScalerImage=arschles/keda-http-scaler:7502948 \
--set interceptorImage=arschles/keda-http-interceptor:7502948
W0204 11:52:22.637173 1743951 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0204 11:52:22.717659 1743951 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0204 11:52:22.797154 1743951 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
Release "kedahttp" has been upgraded. Happy Helming!
NAME: kedahttp
LAST DEPLOYED: Thu Feb  4 11:52:21 2021
NAMESPACE: kedahttp
STATUS: deployed
REVISION: 2
TEST SUITE: None
```

**Comment by khaosdoctor** [comment]
I don't have this SHA on my tree, is this on a local branch?

![image](https://user-images.githubusercontent.com/3200560/106952218-93fe0280-670f-11eb-9476-3ca8aabc84a5.png)

**Comment by khaosdoctor** [comment]
Updated on charts and kustomize:

![image](https://user-images.githubusercontent.com/3200560/109706289-85bcce00-7b77-11eb-906c-d8f269863fbd.png)

Versions are compatible, so nothing more to do
